/**
 * ASM → C Decompiler (pattern-matching)
 * 
 * Recognizes patterns generated by our TinyC compiler and annotates ASM lines
 * with C-like pseudocode descriptions. This is NOT a general-purpose decompiler —
 * it specifically targets the code patterns our compiler emits.
 */

/** Description of what an ASM line or group of lines does in C terms */
export interface DecompAnnotation {
  /** ASM line indices (0-based) this annotation covers */
  asmLines: number[];
  /** C-like pseudocode or description */
  cEquivalent: string;
  /** Category for coloring/grouping */
  category: 'prologue' | 'epilogue' | 'vardecl' | 'assign' | 'condition' | 'loop' | 'call' | 'return' | 'branch' | 'runtime' | 'data' | 'infrastructure';
}

/** Decompile generated assembly back to C-like annotations */
export function decompileAsm(asmText: string): DecompAnnotation[] {
  const lines = asmText.split('\n');
  const annotations: DecompAnnotation[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].trim();

    // Skip empty lines
    if (line === '') { i++; continue; }

    // Comments — compiler header or function comment
    if (line.startsWith('; Generated by') || line.startsWith('; Target:')) {
      annotations.push({ asmLines: [i], cEquivalent: '// Compiler output', category: 'infrastructure' });
      i++; continue;
    }

    // Function comment: "; Function: name"
    const fnComment = line.match(/^; Function: (\w+)/);
    if (fnComment) {
      annotations.push({ asmLines: [i], cEquivalent: `// Function: ${fnComment[1]}()`, category: 'prologue' });
      i++; continue;
    }

    // Built-in comment: "; Built-in: ..."
    if (line.startsWith('; Built-in:')) {
      annotations.push({ asmLines: [i], cEquivalent: `// ${line.substring(2)}`, category: 'runtime' });
      i++; continue;
    }

    // Other comments
    if (line.startsWith(';')) {
      annotations.push({ asmLines: [i], cEquivalent: `// ${line.substring(2)}`, category: 'infrastructure' });
      i++; continue;
    }

    // Function label: "name:"
    const funcLabel = line.match(/^(\w+):$/);
    if (funcLabel) {
      const name = funcLabel[1];
      // Check if this is followed by PUSH {R11} (function prologue)
      if (i + 1 < lines.length && lines[i + 1].trim() === 'PUSH {R11}') {
        // This is a function entry — find the full prologue
        const prologueLines = [i];
        let j = i + 1;
        // Prologue pattern: PUSH {R11}, PUSH {LR}, MOV R11, SP, then optional PUSH {R0-R3} for params
        while (j < lines.length) {
          const l = lines[j].trim();
          if (l === 'PUSH {R11}' || l === 'PUSH {LR}' || l === 'MOV R11, SP' ||
              l.match(/^PUSH \{R[0-3]\}$/)) {
            prologueLines.push(j);
            j++;
          } else {
            break;
          }
        }
        const paramCount = prologueLines.filter(idx =>
          lines[idx].trim().match(/^PUSH \{R[0-3]\}$/) && idx > i + 2
        ).length;
        const paramStr = paramCount > 0 ? `(${Array.from({length: paramCount}, (_, k) => `arg${k}`).join(', ')})` : '()';
        annotations.push({
          asmLines: prologueLines,
          cEquivalent: `// ${name}${paramStr} — function prologue (save frame pointer, return address)`,
          category: 'prologue',
        });
        i = j;
        continue;
      }
      // Epilogue label: "name_epilogue:"
      if (name.endsWith('_epilogue')) {
        const fnName = name.replace('_epilogue', '');
        const epilogueLines = [i];
        let j = i + 1;
        while (j < lines.length) {
          const l = lines[j].trim();
          if (l === 'MOV SP, R11' || l === 'POP {LR}' || l === 'POP {R11}' || l === 'BX LR') {
            epilogueLines.push(j);
            j++;
          } else {
            break;
          }
        }
        annotations.push({
          asmLines: epilogueLines,
          cEquivalent: `// ${fnName}() — function epilogue (restore frame, return)`,
          category: 'epilogue',
        });
        i = j;
        continue;
      }
      // Loop/branch labels
      if (name.match(/^(while|for|dowhile|endwhile|endfor|enddowhile)/)) {
        annotations.push({ asmLines: [i], cEquivalent: `// Loop label: ${name}`, category: 'loop' });
        i++; continue;
      }
      if (name.match(/^(else|endif|if)/)) {
        annotations.push({ asmLines: [i], cEquivalent: `// Branch label: ${name}`, category: 'condition' });
        i++; continue;
      }
      // Runtime function label (putchar, print_num, etc.)
      if (['putchar', 'getchar', 'exit', 'print_num'].includes(name)) {
        annotations.push({ asmLines: [i], cEquivalent: `// Built-in: ${name}()`, category: 'runtime' });
        i++; continue;
      }
      // Global variable label
      if (name.startsWith('_g_')) {
        annotations.push({ asmLines: [i], cEquivalent: `// Global: ${name.substring(3)}`, category: 'data' });
        i++; continue;
      }
      // Generic label
      annotations.push({ asmLines: [i], cEquivalent: `// Label: ${name}`, category: 'branch' });
      i++; continue;
    }

    // BL main — program entry
    if (line === 'BL main') {
      annotations.push({ asmLines: [i], cEquivalent: 'main();  // call main()', category: 'infrastructure' });
      i++; continue;
    }

    // HALT
    if (line === 'HALT') {
      annotations.push({ asmLines: [i], cEquivalent: '// program exit', category: 'infrastructure' });
      i++; continue;
    }

    // BL func — function call
    const blMatch = line.match(/^BL (\w+)/);
    if (blMatch) {
      annotations.push({ asmLines: [i], cEquivalent: `${blMatch[1]}(...)`, category: 'call' });
      i++; continue;
    }

    // BX LR — return from function
    if (line === 'BX LR') {
      annotations.push({ asmLines: [i], cEquivalent: 'return', category: 'return' });
      i++; continue;
    }

    // SWI #N — system call
    const swiMatch = line.match(/^SWI #(\d+)/);
    if (swiMatch) {
      const num = parseInt(swiMatch[1]);
      const syscallNames: Record<number, string> = { 11: 'putchar(R0)', 12: 'getchar() → R0' };
      annotations.push({
        asmLines: [i],
        cEquivalent: `__syscall(${num})  // ${syscallNames[num] || 'unknown'}`,
        category: 'call',
      });
      i++; continue;
    }

    // MOV R0, #N — load immediate
    const movImm = line.match(/^MOV R(\d+), #(-?\d+)/);
    if (movImm) {
      const reg = parseInt(movImm[1]);
      const val = parseInt(movImm[2]);
      // Check if it's an ASCII printable character
      const charStr = (val >= 32 && val <= 126) ? ` ('${String.fromCharCode(val)}')` : '';
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${reg} = ${val}${charStr}`,
        category: 'assign',
      });
      i++; continue;
    }

    // MOVcc R0, #N — conditional move (part of comparison result)
    const movcond = line.match(/^MOV(LT|GT|LE|GE|EQ|NE) R(\d+), #(\d+)/);
    if (movcond) {
      const condMap: Record<string, string> = {
        'LT': '<', 'GT': '>', 'LE': '<=', 'GE': '>=', 'EQ': '==', 'NE': '!=',
      };
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${movcond[2]} = ${movcond[3]} if ${condMap[movcond[1]] || movcond[1]}  // boolean result`,
        category: 'condition',
      });
      i++; continue;
    }

    // CMP Rn, Rm or CMP Rn, #imm
    const cmpMatch = line.match(/^CMP R(\d+), (R\d+|#-?\d+)/);
    if (cmpMatch) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `compare R${cmpMatch[1]} with ${cmpMatch[2]}`,
        category: 'condition',
      });
      i++; continue;
    }

    // Branch instructions
    const branchMatch = line.match(/^B(EQ|NE|LT|GT|LE|GE)?\s+(\w+)/);
    if (branchMatch && !line.startsWith('BL ') && !line.startsWith('BX ')) {
      const cond = branchMatch[1];
      const target = branchMatch[2];
      if (cond) {
        const condMap: Record<string, string> = {
          'EQ': 'if equal', 'NE': 'if not equal',
          'LT': 'if less', 'GT': 'if greater',
          'LE': 'if less or equal', 'GE': 'if greater or equal',
        };
        annotations.push({
          asmLines: [i],
          cEquivalent: `goto ${target} ${condMap[cond] || cond}`,
          category: 'branch',
        });
      } else {
        annotations.push({
          asmLines: [i],
          cEquivalent: `goto ${target}`,
          category: 'branch',
        });
      }
      i++; continue;
    }

    // PUSH {Rn} — save to stack
    const pushMatch = line.match(/^PUSH \{(R\d+(?:, R\d+)*(?:, LR)?)\}/);
    if (pushMatch) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `push ${pushMatch[1]} onto stack`,
        category: 'assign',
      });
      i++; continue;
    }

    // POP {Rn}
    const popMatch = line.match(/^POP \{(R\d+(?:, R\d+)*(?:, LR)?)\}/);
    if (popMatch) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `pop ${popMatch[1]} from stack`,
        category: 'assign',
      });
      i++; continue;
    }

    // LDR Rn, [R11, #-offset] — load local variable
    const ldrLocal = line.match(/^LDR R(\d+), \[R11, #-(\d+)\]/);
    if (ldrLocal) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${ldrLocal[1]} = local_var  // [FP - ${ldrLocal[2]}]`,
        category: 'assign',
      });
      i++; continue;
    }

    // STR Rn, [R11, #-offset] — store local variable
    const strLocal = line.match(/^STR R(\d+), \[R11, #-(\d+)\]/);
    if (strLocal) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `local_var = R${strLocal[1]}  // [FP - ${strLocal[2]}]`,
        category: 'assign',
      });
      i++; continue;
    }

    // LDR/STR with register base
    const memOp = line.match(/^(LDR|STR) R(\d+), \[R(\d+)(.*?)\]/);
    if (memOp) {
      const op = memOp[1] === 'LDR' ? 'load' : 'store';
      annotations.push({
        asmLines: [i],
        cEquivalent: `${op} R${memOp[2]} ↔ memory[R${memOp[3]}${memOp[4]}]`,
        category: 'assign',
      });
      i++; continue;
    }

    // Arithmetic: ADD, SUB, MUL, DIV, MOD
    const arith = line.match(/^(ADD|SUB|MUL|DIV|MOD) R(\d+), R(\d+), (R\d+|#-?\d+)/);
    if (arith) {
      const opMap: Record<string, string> = { 'ADD': '+', 'SUB': '-', 'MUL': '*', 'DIV': '/', 'MOD': '%' };
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${arith[2]} = R${arith[3]} ${opMap[arith[1]]} ${arith[4]}`,
        category: 'assign',
      });
      i++; continue;
    }

    // Bitwise: AND, ORR, EOR
    const bitwise = line.match(/^(AND|ORR|EOR) R(\d+), R(\d+), (R\d+|#-?\d+)/);
    if (bitwise) {
      const opMap: Record<string, string> = { 'AND': '&', 'ORR': '|', 'EOR': '^' };
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${bitwise[2]} = R${bitwise[3]} ${opMap[bitwise[1]]} ${bitwise[4]}`,
        category: 'assign',
      });
      i++; continue;
    }

    // MOV SP, R11 — restore stack pointer
    if (line === 'MOV SP, R11') {
      annotations.push({ asmLines: [i], cEquivalent: 'SP = FP  // restore stack', category: 'epilogue' });
      i++; continue;
    }

    // MOV Rd, Rs
    const movReg = line.match(/^MOV R(\d+), R(\d+)/);
    if (movReg) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${movReg[1]} = R${movReg[2]}`,
        category: 'assign',
      });
      i++; continue;
    }

    // MOVW/MOVT — wide immediate / global address load
    const movw = line.match(/^MOVW R(\d+), #(\w+)/);
    if (movw) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `R${movw[1]} = &${movw[2]}  // load address (low 16 bits)`,
        category: 'assign',
      });
      i++; continue;
    }

    // .word directive — data
    const wordDir = line.match(/^\.word\s+(.+)/);
    if (wordDir) {
      annotations.push({ asmLines: [i], cEquivalent: `= ${wordDir[1]}  // data`, category: 'data' });
      i++; continue;
    }

    // .asciz directive — string literal
    const asciz = line.match(/^\.asciz\s+"(.*)"/);
    if (asciz) {
      annotations.push({ asmLines: [i], cEquivalent: `= "${asciz[1]}"  // string`, category: 'data' });
      i++; continue;
    }

    // STR SP, [R11, #-N] — loop SP save
    const spSave = line.match(/^STR SP, \[R11, #-(\d+)\]/);
    if (spSave) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `// save stack pointer for loop cleanup`,
        category: 'loop',
      });
      i++; continue;
    }

    // LDR SP, [R11, #-N] — loop SP restore
    const spRestore = line.match(/^LDR SP, \[R11, #-(\d+)\]/);
    if (spRestore) {
      annotations.push({
        asmLines: [i],
        cEquivalent: `// restore stack pointer (loop iteration cleanup)`,
        category: 'loop',
      });
      i++; continue;
    }

    // Catch-all for unrecognized lines
    annotations.push({ asmLines: [i], cEquivalent: line, category: 'infrastructure' });
    i++;
  }

  return annotations;
}
